on: push
name: Pytest
jobs:
  gitHubActionForPytest:
    name: pytest classify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: pytest -k classify
